### ISSUE TITLE
Site Meta Components

### ISSUE THREAD

**Issue by owenvoke** [PXgamer/cwtch-potato#4]
### Movies
- [x] TMDb [themoviedb.org](https://www.themoviedb.org/)  
- [x] Wrapper: https://packagist.org/packages/php-tmdb/api

### TV Shows
- [x] TMDb [themoviedb.org](https://www.themoviedb.org/)  
- [x] Wrapper: https://packagist.org/packages/php-tmdb/api

### Games
- [x] IGDb [igdb.com](https://igdb.com)  
- [x] Wrapper: https://packagist.org/packages/ynotna/igdb-php

### Books
- [ ] OpenLibrary [openlibrary.org](https://openlibrary.org)  
- [ ] Wrapper: https://packagist.org/packages/beezus/openlibrary-php
